import { CancelDeploy } from "../definitions/CancelDeploy";
import { CancelDeployResponse } from "../definitions/CancelDeployResponse";
import { CheckDeployStatus } from "../definitions/CheckDeployStatus";
import { CheckDeployStatusResponse } from "../definitions/CheckDeployStatusResponse";
import { CheckRetrieveStatus } from "../definitions/CheckRetrieveStatus";
import { CheckRetrieveStatusResponse } from "../definitions/CheckRetrieveStatusResponse";
import { CreateMetadata } from "../definitions/CreateMetadata";
import { CreateMetadataResponse } from "../definitions/CreateMetadataResponse";
import { DeleteMetadata } from "../definitions/DeleteMetadata";
import { DeleteMetadataResponse } from "../definitions/DeleteMetadataResponse";
import { Deploy } from "../definitions/Deploy";
import { DeployResponse } from "../definitions/DeployResponse";
import { DeployRecentValidation } from "../definitions/DeployRecentValidation";
import { DeployRecentValidationResponse } from "../definitions/DeployRecentValidationResponse";
import { DescribeMetadata } from "../definitions/DescribeMetadata";
import { DescribeMetadataResponse } from "../definitions/DescribeMetadataResponse";
import { DescribeValueType } from "../definitions/DescribeValueType";
import { DescribeValueTypeResponse } from "../definitions/DescribeValueTypeResponse";
import { ListMetadata } from "../definitions/ListMetadata";
import { ListMetadataResponse } from "../definitions/ListMetadataResponse";
import { ReadMetadata } from "../definitions/ReadMetadata";
import { ReadMetadataResponse } from "../definitions/ReadMetadataResponse";
import { RenameMetadata } from "../definitions/RenameMetadata";
import { RenameMetadataResponse } from "../definitions/RenameMetadataResponse";
import { Retrieve } from "../definitions/Retrieve";
import { RetrieveResponse } from "../definitions/RetrieveResponse";
import { UpdateMetadata } from "../definitions/UpdateMetadata";
import { UpdateMetadataResponse } from "../definitions/UpdateMetadataResponse";
import { UpsertMetadata } from "../definitions/UpsertMetadata";
import { UpsertMetadataResponse } from "../definitions/UpsertMetadataResponse";

export interface Metadata {
    cancelDeploy(cancelDeploy: CancelDeploy, callback: (err: any, result: CancelDeployResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    checkDeployStatus(checkDeployStatus: CheckDeployStatus, callback: (err: any, result: CheckDeployStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    checkRetrieveStatus(checkRetrieveStatus: CheckRetrieveStatus, callback: (err: any, result: CheckRetrieveStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    createMetadata(createMetadata: CreateMetadata, callback: (err: any, result: CreateMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    deleteMetadata(deleteMetadata: DeleteMetadata, callback: (err: any, result: DeleteMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    deploy(deploy: Deploy, callback: (err: any, result: DeployResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    deployRecentValidation(deployRecentValidation: DeployRecentValidation, callback: (err: any, result: DeployRecentValidationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeMetadata(describeMetadata: DescribeMetadata, callback: (err: any, result: DescribeMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeValueType(describeValueType: DescribeValueType, callback: (err: any, result: DescribeValueTypeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    listMetadata(listMetadata: ListMetadata, callback: (err: any, result: ListMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    readMetadata(readMetadata: ReadMetadata, callback: (err: any, result: ReadMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    renameMetadata(renameMetadata: RenameMetadata, callback: (err: any, result: RenameMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    retrieve(retrieve: Retrieve, callback: (err: any, result: RetrieveResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    updateMetadata(updateMetadata: UpdateMetadata, callback: (err: any, result: UpdateMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    upsertMetadata(upsertMetadata: UpsertMetadata, callback: (err: any, result: UpsertMetadataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
