import { Login } from "../definitions/Login";
import { LoginResponse } from "../definitions/LoginResponse";
import { DescribeSObject } from "../definitions/DescribeSObject";
import { DescribeSObjectResponse } from "../definitions/DescribeSObjectResponse";
import { DescribeSObjects } from "../definitions/DescribeSObjects";
import { DescribeSObjectsResponse } from "../definitions/DescribeSObjectsResponse";
import { DescribeGlobal } from "../definitions/DescribeGlobal";
import { DescribeGlobalResponse } from "../definitions/DescribeGlobalResponse";
import { DescribeDataCategoryGroups } from "../definitions/DescribeDataCategoryGroups";
import { DescribeDataCategoryGroupsResponse } from "../definitions/DescribeDataCategoryGroupsResponse";
import { DescribeDataCategoryGroupStructures } from "../definitions/DescribeDataCategoryGroupStructures";
import { DescribeDataCategoryGroupStructuresResponse } from "../definitions/DescribeDataCategoryGroupStructuresResponse";
import { DescribeDataCategoryMappings } from "../definitions/DescribeDataCategoryMappings";
import { DescribeDataCategoryMappingsResponse } from "../definitions/DescribeDataCategoryMappingsResponse";
import { DescribeKnowledgeSettings } from "../definitions/DescribeKnowledgeSettings";
import { DescribeKnowledgeSettingsResponse } from "../definitions/DescribeKnowledgeSettingsResponse";
import { DescribeAppMenu } from "../definitions/DescribeAppMenu";
import { DescribeAppMenuResponse } from "../definitions/DescribeAppMenuResponse";
import { DescribeGlobalTheme } from "../definitions/DescribeGlobalTheme";
import { DescribeGlobalThemeResponse } from "../definitions/DescribeGlobalThemeResponse";
import { DescribeTheme } from "../definitions/DescribeTheme";
import { DescribeThemeResponse } from "../definitions/DescribeThemeResponse";
import { DescribeLayout } from "../definitions/DescribeLayout";
import { DescribeLayoutResponse } from "../definitions/DescribeLayoutResponse";
import { DescribeSoftphoneLayout } from "../definitions/DescribeSoftphoneLayout";
import { DescribeSoftphoneLayoutResponse } from "../definitions/DescribeSoftphoneLayoutResponse";
import { DescribeSearchLayouts } from "../definitions/DescribeSearchLayouts";
import { DescribeSearchLayoutsResponse } from "../definitions/DescribeSearchLayoutsResponse";
import { DescribeSearchableEntities } from "../definitions/DescribeSearchableEntities";
import { DescribeSearchableEntitiesResponse } from "../definitions/DescribeSearchableEntitiesResponse";
import { DescribeSearchScopeOrder } from "../definitions/DescribeSearchScopeOrder";
import { DescribeSearchScopeOrderResponse } from "../definitions/DescribeSearchScopeOrderResponse";
import { DescribeCompactLayouts } from "../definitions/DescribeCompactLayouts";
import { DescribeCompactLayoutsResponse } from "../definitions/DescribeCompactLayoutsResponse";
import { DescribePathAssistants } from "../definitions/DescribePathAssistants";
import { DescribePathAssistantsResponse } from "../definitions/DescribePathAssistantsResponse";
import { DescribeApprovalLayout } from "../definitions/DescribeApprovalLayout";
import { DescribeApprovalLayoutResponse } from "../definitions/DescribeApprovalLayoutResponse";
import { DescribeSoqlListViews } from "../definitions/DescribeSoqlListViews";
import { DescribeSoqlListViewsResponse } from "../definitions/DescribeSoqlListViewsResponse";
import { ExecuteListView } from "../definitions/ExecuteListView";
import { ExecuteListViewResponse } from "../definitions/ExecuteListViewResponse";
import { DescribeSObjectListViews } from "../definitions/DescribeSObjectListViews";
import { DescribeSObjectListViewsResponse } from "../definitions/DescribeSObjectListViewsResponse";
import { DescribeTabs } from "../definitions/DescribeTabs";
import { DescribeTabsResponse } from "../definitions/DescribeTabsResponse";
import { DescribeAllTabs } from "../definitions/DescribeAllTabs";
import { DescribeAllTabsResponse } from "../definitions/DescribeAllTabsResponse";
import { DescribePrimaryCompactLayouts } from "../definitions/DescribePrimaryCompactLayouts";
import { DescribePrimaryCompactLayoutsResponse } from "../definitions/DescribePrimaryCompactLayoutsResponse";
import { Create } from "../definitions/Create";
import { CreateResponse } from "../definitions/CreateResponse";
import { Update } from "../definitions/Update";
import { UpdateResponse } from "../definitions/UpdateResponse";
import { Upsert } from "../definitions/Upsert";
import { UpsertResponse } from "../definitions/UpsertResponse";
import { Merge } from "../definitions/Merge";
import { MergeResponse } from "../definitions/MergeResponse";
import { Delete } from "../definitions/Delete";
import { DeleteResponse } from "../definitions/DeleteResponse";
import { Undelete } from "../definitions/Undelete";
import { UndeleteResponse } from "../definitions/UndeleteResponse";
import { EmptyRecycleBin } from "../definitions/EmptyRecycleBin";
import { EmptyRecycleBinResponse } from "../definitions/EmptyRecycleBinResponse";
import { Retrieve } from "../definitions/Retrieve";
import { RetrieveResponse } from "../definitions/RetrieveResponse";
import { Process } from "../definitions/Process";
import { ProcessResponse } from "../definitions/ProcessResponse";
import { ConvertLead } from "../definitions/ConvertLead";
import { ConvertLeadResponse } from "../definitions/ConvertLeadResponse";
import { Logout } from "../definitions/Logout";
import { LogoutResponse } from "../definitions/LogoutResponse";
import { InvalidateSessions } from "../definitions/InvalidateSessions";
import { InvalidateSessionsResponse } from "../definitions/InvalidateSessionsResponse";
import { GetDeleted } from "../definitions/GetDeleted";
import { GetDeletedResponse } from "../definitions/GetDeletedResponse";
import { GetUpdated } from "../definitions/GetUpdated";
import { GetUpdatedResponse } from "../definitions/GetUpdatedResponse";
import { Query } from "../definitions/Query";
import { QueryResponse } from "../definitions/QueryResponse";
import { QueryAll } from "../definitions/QueryAll";
import { QueryAllResponse } from "../definitions/QueryAllResponse";
import { QueryMore } from "../definitions/QueryMore";
import { QueryMoreResponse } from "../definitions/QueryMoreResponse";
import { Search } from "../definitions/Search";
import { SearchResponse } from "../definitions/SearchResponse";
import { GetServerTimestamp } from "../definitions/GetServerTimestamp";
import { GetServerTimestampResponse } from "../definitions/GetServerTimestampResponse";
import { SetPassword } from "../definitions/SetPassword";
import { SetPasswordResponse } from "../definitions/SetPasswordResponse";
import { ChangeOwnPassword } from "../definitions/ChangeOwnPassword";
import { ChangeOwnPasswordResponse } from "../definitions/ChangeOwnPasswordResponse";
import { ResetPassword } from "../definitions/ResetPassword";
import { ResetPasswordResponse } from "../definitions/ResetPasswordResponse";
import { GetUserInfo } from "../definitions/GetUserInfo";
import { GetUserInfoResponse } from "../definitions/GetUserInfoResponse";
import { DeleteByExample } from "../definitions/DeleteByExample";
import { DeleteByExampleResponse } from "../definitions/DeleteByExampleResponse";
import { SendEmailMessage } from "../definitions/SendEmailMessage";
import { SendEmailMessageResponse } from "../definitions/SendEmailMessageResponse";
import { SendEmail } from "../definitions/SendEmail";
import { SendEmailResponse } from "../definitions/SendEmailResponse";
import { RenderEmailTemplate } from "../definitions/RenderEmailTemplate";
import { RenderEmailTemplateResponse } from "../definitions/RenderEmailTemplateResponse";
import { RenderStoredEmailTemplate } from "../definitions/RenderStoredEmailTemplate";
import { RenderStoredEmailTemplateResponse } from "../definitions/RenderStoredEmailTemplateResponse";
import { PerformQuickActions } from "../definitions/PerformQuickActions";
import { PerformQuickActionsResponse } from "../definitions/PerformQuickActionsResponse";
import { DescribeQuickActions } from "../definitions/DescribeQuickActions";
import { DescribeQuickActionsResponse } from "../definitions/DescribeQuickActionsResponse";
import { DescribeQuickActionsForRecordType } from "../definitions/DescribeQuickActionsForRecordType";
import { DescribeQuickActionsForRecordTypeResponse } from "../definitions/DescribeQuickActionsForRecordTypeResponse";
import { DescribeAvailableQuickActions } from "../definitions/DescribeAvailableQuickActions";
import { DescribeAvailableQuickActionsResponse } from "../definitions/DescribeAvailableQuickActionsResponse";
import { RetrieveQuickActionTemplates } from "../definitions/RetrieveQuickActionTemplates";
import { RetrieveQuickActionTemplatesResponse } from "../definitions/RetrieveQuickActionTemplatesResponse";
import { RetrieveMassQuickActionTemplates } from "../definitions/RetrieveMassQuickActionTemplates";
import { RetrieveMassQuickActionTemplatesResponse } from "../definitions/RetrieveMassQuickActionTemplatesResponse";
import { DescribeVisualForce } from "../definitions/DescribeVisualForce";
import { DescribeVisualForceResponse } from "../definitions/DescribeVisualForceResponse";
import { FindDuplicates } from "../definitions/FindDuplicates";
import { FindDuplicatesResponse } from "../definitions/FindDuplicatesResponse";
import { FindDuplicatesByIds } from "../definitions/FindDuplicatesByIds";
import { FindDuplicatesByIdsResponse } from "../definitions/FindDuplicatesByIdsResponse";
import { DescribeNouns } from "../definitions/DescribeNouns";
import { DescribeNounsResponse } from "../definitions/DescribeNounsResponse";

export interface Soap {
    login(login: Login, callback: (err: any, result: LoginResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSObject(describeSObject: DescribeSObject, callback: (err: any, result: DescribeSObjectResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSObjects(describeSObjects: DescribeSObjects, callback: (err: any, result: DescribeSObjectsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeGlobal(describeGlobal: DescribeGlobal, callback: (err: any, result: DescribeGlobalResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeDataCategoryGroups(describeDataCategoryGroups: DescribeDataCategoryGroups, callback: (err: any, result: DescribeDataCategoryGroupsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeDataCategoryGroupStructures(describeDataCategoryGroupStructures: DescribeDataCategoryGroupStructures, callback: (err: any, result: DescribeDataCategoryGroupStructuresResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeDataCategoryMappings(describeDataCategoryMappings: DescribeDataCategoryMappings, callback: (err: any, result: DescribeDataCategoryMappingsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeKnowledgeSettings(describeKnowledgeSettings: DescribeKnowledgeSettings, callback: (err: any, result: DescribeKnowledgeSettingsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeAppMenu(describeAppMenu: DescribeAppMenu, callback: (err: any, result: DescribeAppMenuResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeGlobalTheme(describeGlobalTheme: DescribeGlobalTheme, callback: (err: any, result: DescribeGlobalThemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeTheme(describeTheme: DescribeTheme, callback: (err: any, result: DescribeThemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeLayout(describeLayout: DescribeLayout, callback: (err: any, result: DescribeLayoutResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSoftphoneLayout(describeSoftphoneLayout: DescribeSoftphoneLayout, callback: (err: any, result: DescribeSoftphoneLayoutResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSearchLayouts(describeSearchLayouts: DescribeSearchLayouts, callback: (err: any, result: DescribeSearchLayoutsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSearchableEntities(describeSearchableEntities: DescribeSearchableEntities, callback: (err: any, result: DescribeSearchableEntitiesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSearchScopeOrder(describeSearchScopeOrder: DescribeSearchScopeOrder, callback: (err: any, result: DescribeSearchScopeOrderResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeCompactLayouts(describeCompactLayouts: DescribeCompactLayouts, callback: (err: any, result: DescribeCompactLayoutsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describePathAssistants(describePathAssistants: DescribePathAssistants, callback: (err: any, result: DescribePathAssistantsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeApprovalLayout(describeApprovalLayout: DescribeApprovalLayout, callback: (err: any, result: DescribeApprovalLayoutResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSoqlListViews(describeSoqlListViews: DescribeSoqlListViews, callback: (err: any, result: DescribeSoqlListViewsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    executeListView(executeListView: ExecuteListView, callback: (err: any, result: ExecuteListViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeSObjectListViews(describeSObjectListViews: DescribeSObjectListViews, callback: (err: any, result: DescribeSObjectListViewsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeTabs(describeTabs: DescribeTabs, callback: (err: any, result: DescribeTabsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeAllTabs(describeAllTabs: DescribeAllTabs, callback: (err: any, result: DescribeAllTabsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describePrimaryCompactLayouts(describePrimaryCompactLayouts: DescribePrimaryCompactLayouts, callback: (err: any, result: DescribePrimaryCompactLayoutsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    create(create: Create, callback: (err: any, result: CreateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    update(update: Update, callback: (err: any, result: UpdateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    upsert(upsert: Upsert, callback: (err: any, result: UpsertResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    merge(merge: Merge, callback: (err: any, result: MergeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    delete(deleteParam: Delete, callback: (err: any, result: DeleteResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    undelete(undelete: Undelete, callback: (err: any, result: UndeleteResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    emptyRecycleBin(emptyRecycleBin: EmptyRecycleBin, callback: (err: any, result: EmptyRecycleBinResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    retrieve(retrieve: Retrieve, callback: (err: any, result: RetrieveResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    process(process: Process, callback: (err: any, result: ProcessResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    convertLead(convertLead: ConvertLead, callback: (err: any, result: ConvertLeadResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    logout(logout: Logout, callback: (err: any, result: LogoutResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    invalidateSessions(invalidateSessions: InvalidateSessions, callback: (err: any, result: InvalidateSessionsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    getDeleted(getDeleted: GetDeleted, callback: (err: any, result: GetDeletedResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    getUpdated(getUpdated: GetUpdated, callback: (err: any, result: GetUpdatedResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    query(query: Query, callback: (err: any, result: QueryResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    queryAll(queryAll: QueryAll, callback: (err: any, result: QueryAllResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    queryMore(queryMore: QueryMore, callback: (err: any, result: QueryMoreResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    search(search: Search, callback: (err: any, result: SearchResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    getServerTimestamp(getServerTimestamp: GetServerTimestamp, callback: (err: any, result: GetServerTimestampResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    setPassword(setPassword: SetPassword, callback: (err: any, result: SetPasswordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    changeOwnPassword(changeOwnPassword: ChangeOwnPassword, callback: (err: any, result: ChangeOwnPasswordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    resetPassword(resetPassword: ResetPassword, callback: (err: any, result: ResetPasswordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    getUserInfo(getUserInfo: GetUserInfo, callback: (err: any, result: GetUserInfoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    deleteByExample(deleteByExample: DeleteByExample, callback: (err: any, result: DeleteByExampleResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sendEmailMessage(sendEmailMessage: SendEmailMessage, callback: (err: any, result: SendEmailMessageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sendEmail(sendEmail: SendEmail, callback: (err: any, result: SendEmailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    renderEmailTemplate(renderEmailTemplate: RenderEmailTemplate, callback: (err: any, result: RenderEmailTemplateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    renderStoredEmailTemplate(renderStoredEmailTemplate: RenderStoredEmailTemplate, callback: (err: any, result: RenderStoredEmailTemplateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    performQuickActions(performQuickActions: PerformQuickActions, callback: (err: any, result: PerformQuickActionsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeQuickActions(describeQuickActions: DescribeQuickActions, callback: (err: any, result: DescribeQuickActionsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeQuickActionsForRecordType(describeQuickActionsForRecordType: DescribeQuickActionsForRecordType, callback: (err: any, result: DescribeQuickActionsForRecordTypeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeAvailableQuickActions(describeAvailableQuickActions: DescribeAvailableQuickActions, callback: (err: any, result: DescribeAvailableQuickActionsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    retrieveQuickActionTemplates(retrieveQuickActionTemplates: RetrieveQuickActionTemplates, callback: (err: any, result: RetrieveQuickActionTemplatesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    retrieveMassQuickActionTemplates(retrieveMassQuickActionTemplates: RetrieveMassQuickActionTemplates, callback: (err: any, result: RetrieveMassQuickActionTemplatesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeVisualForce(describeVisualForce: DescribeVisualForce, callback: (err: any, result: DescribeVisualForceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    findDuplicates(findDuplicates: FindDuplicates, callback: (err: any, result: FindDuplicatesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    findDuplicatesByIds(findDuplicatesByIds: FindDuplicatesByIds, callback: (err: any, result: FindDuplicatesByIdsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    describeNouns(describeNouns: DescribeNouns, callback: (err: any, result: DescribeNounsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
